version: '3.4'
name: pg_aspnet_identity

services:
  postgresidentitysample:
    image: ${DOCKER_REGISTRY-}postgresidentitysample
    build:
      context: .
      dockerfile: PostgresIdentitySample/Dockerfile
    container_name: identity_server
    ports:
    - 15002:8080
    - 15003:8081
    depends_on:
    - identity

  identity:
    image: postgres
    container_name: identity_db
    environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_USER=postgres
    - POSTGRES_DB=postgres
    ports:
    - 15001:5432